name: Run Jest tests on push

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund
      - name: Run Jest tests
        run: |
          npx jest --ci --coverage

  deploy-prod:
    if: github.ref == 'refs/heads/master' && always() && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs: [test]
    uses: mnofresno/github-autodeploy/.github/workflows/reusable-deploy.yml@master
    with:
      autodeploy_url: ${{ vars.AUTODEPLOY_URL }}
      deploy_key: placeholder
      repository: mariano-portfolio
      commit_sha: ${{ github.sha }}
      commit_author: ${{ github.actor }}
    secrets:
      KEY_FILE_FOR_DEPLOY: ${{ secrets.KEY_FILE_FOR_DEPLOY }}
